version: '3.9'

services:
  client:
    container_name: clientapp
    image: clientimage
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - yolomyapp-network
    stdin_open: true
  api:
    container_name: backendapp
    image: backendimage
    build:
      context: ./backend
      dockerfile: Dockerfile      
    ports:
      - "5000:5000"
    networks:
      - yolomyapp-network
    volumes:
      - ./logs:/var/www/logs
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=yolomy
    depends_on: 
      - mongodb
      
  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    networks:
      - yolomyapp-network
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
volumes:
  mongo_db:
networks:
  yolomyapp-network:
    driver: bridge