version: '3.9'

services:
#front end client app to run on port 3000, depends on api(api) has to run first
  client:
    container_name: clientapp
    image: skalume/yoloclientimage:v1.0.0
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - yolomyapp-network
    stdin_open: true
#here I create the backend container which runs on port 5000, from backend folder uses same network as clientapp, depends on mongodb container
  api:
    container_name: backendapp
    image: skalume/yolobackendimage:v1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile      
    ports:
      - "5000:5000"
    networks:
      - yolomyapp-network
    #env_file:
    #  - ./backend/.env
    volumes:
      - ./logs:/var/www/logs
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=yolomy
    depends_on: 
      - mongodb
#here i create the mongodb container using latest mongo image, runs on 27017 and same network with other containers      
  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    networks:
      - yolomyapp-network
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
volumes:
  mongo_db:
networks:
  yolomyapp-network:
    driver: bridge