apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
data:
  mongodb-uri: "bW9uZ29kYitzcnY6Ly9zYW1zb25rYWx1bWU6U2FAa2FANDIwTkBtb3JpbmdhLmtlZ3Y0eG0ubW9uZ29kYi5uZXQveW9sb215P3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ=="
