---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server-statefulset
  annotations:
    description: "This is a yaml file for creating a backend pod and mongo , its a stateful set"
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: skalume/yolobackendimage:v1.0.0
        ports:
        - containerPort: 5000
        env:
  - name: MONGODB_URI
    valueFrom:
      secretKeyRef:
        name: my-secrets
        key: mongodb-uri
        volumeMounts:
        - name: data
          mountPath: /app/data
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: server-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
